### ISSUE TITLE
Can this be used with Sinatra?

### ISSUE THREAD

**Issue by kris-luminar** [faradayio/hangar#7]
We've got a Sinatra API as a back-end for our Angular app.  We'd love to use this project to manage database state in our Protractor tests but haven't been able to figure out how to get it to work. Do you have any suggestions?

**Comment by kris-luminar** [comment]
I'm investigating reworking this project for Sinatra. Do you know if a gem to inject routes can work with both Rails and Sinatra? My first guess would be that I'd have to create a new, Sinatra-specific gem and alter your code substantially to get it to work.

**Comment by kris-luminar** [comment]
> I'm not familiar enough with Sinatra to know if a gem can inject routes---do you know?

Yes, Sinatra supports that. It looks pretty easy to inject routes in Sinatra using Sinatra Extensions (example: http://www.sinatrarb.com/extensions.html#setting-options-and-other-extension-setup ).

I don't think I could realistically know if it's possible to to make Hanger work in both Rails and Sinatra without first creating at least a bare-bones Sinatra specific version so we could compare the code between the two projects and then decide if merging them is worthwhile.

How would you feel about me using a lot of the code in faradayio/hangar in a new Sinatra Hangar gem? I would of course keep the MIT license and give this project credit in the README.

**Comment by rossmeissl** [comment]
HI @kris-luminar of course you're welcome to start a new project, although I think building Sinatra support into this codebase might not be too tough. When this gem is loaded into a Rails app, it subclasses `Rails::Engine` [here](https://github.com/faradayio/hangar/blob/master/lib/hangar/engine.rb) which Rails notices and uses as a trigger to absorb Hangar into the app.

I think the first step would be to only [`require hangar/engine`](https://github.com/faradayio/hangar/blob/master/lib/hangar.rb#L1) if `Rails` is around, and require a different boostrapper if `Sinatra` is around. Driver pattern, I guess.

**Comment by kris-luminar** [comment]
That's encouraging. I'll probably re-visit adding Sinatra support to this gem then.

**Comment by rossmeissl** [comment]
@kris-luminar any progress on this?

**Comment by kris-luminar** [comment]
I @rossmeissl. Appreciate you following up on this, but I abandoned this project.
