### ISSUE TITLE
Accept factory traits

### ISSUE THREAD

**Issue by ronaldotijucas** [faradayio/hangar#9]
Hello, thanks for that awesome Gem!

I needed and thought about implementing the feature to this accept traits, however, I found this functionality in the @michbert's hangar fork (https://github.com/michbert/hangar/commit/af7ff0e5233b51c4b53c4928c446809481150b41).

Did you already think about get this PR?

**Comment by letmein** [comment]
Hi! I've created my own web iterface for FactorGirl with trait support. Maybe my approach can be used in this gem too.

Rails controller:
```ruby
  def create
    render json: FactoryGirl.create(*params[:factory]).to_json
  end
```
Coffee:
```coffee
  create: ->
    options =
      url:    "#{browser.baseUrl}/factory_girl"
      method: 'POST'
      json:   true
      body:
        factory: Array::slice.call arguments
    request options, (error, response, body) ->
```
Then in js tests I use it like this: `FactoryGirl.create 'user', 'trait1', 'trait2', name: 'Foo', email: 'test@example.com'` -- exactly same way as in Rails.

**Comment by rossmeissl** [comment]
@ronaldotijucas I'm discussing @michbert's fork with him now—thanks.

@letmein have you seen https://github.com/faradayio/hangarjs ?

**Comment by letmein** [comment]
@rossmeissl sure, seen and used it, but it lacked traits. My version is less restful, though it's simpler..

**Comment by rossmeissl** [comment]
Traits are working now
